name: ByteplexMatches
version: 2018.3.26.1
author:
 - Stellaric
 - WillOCN
 - Guitaric
 - sierek_1337
main: net.byteplex.ByteplexMatches.ByteplexMatches
commands:
  setloc:
    description: Set your spawn location by looking at it
    usage: /setloc
  team:
    description: Place yourself on a team
    usage: /team <red/blue>
softdepend: [ProtocolLib]